#!/bin/bash
# add a wpa_supplicant config to your configs

CONFIG_PATH="$HOME/.wpa"
WPA_GROUP="wheel"
HIDDEN=0

for i in $*
do
	case $i in
		'--hidden')
			HIDDEN=1
			;;
	esac
done


cd $CONFIG_PATH

echo "Tell us the network name (name of config file)"
read NAME
echo "Now we need the ssid"
read SSID
echo "Finally we need the password"
stty -echo
read  -r PW

if [ -d .wpa ]
then
	echo "First config file... creating config directory"
	mkdir $HOME/.wpa
fi

if [ ! -f $NAME.conf ]
then
	echo "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=$WPA_GROUP" >> $NAME.conf
	echo "update_config=1" >> $NAME.conf
else
	echo "file already exists -> append config!"
fi
echo "" >> $NAME.conf
echo -e "network={" >> $NAME.conf
echo -e "\tssid=\"$SSID\"" >> $NAME.conf
echo -e "\tscan_ssid=$HIDDEN" >> $NAME.conf
#echo -e "\tproto=WPA RSN" >> $NAME.conf
echo -e "\tkey_mgmt=WPA-PSK" >> $NAME.conf
#echo -e "\tgroup=CCMP TKIP" >> $NAME.conf
echo -e "\tpsk=\"$PW\"" >> $NAME.conf
echo -e "}" >> $NAME.conf

echo "set permissions"
chown $USER:$WPA_GROUP $CONFIG_PATH/$NAME.conf
chmod 660 $CONFIG_PATH/$NAME.conf

echo "created config file:"
echo "$CONFIG_PATH/$NAME.conf"
